
  create table "public"."dummy" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."dummy" enable row level security;

CREATE UNIQUE INDEX dummy_pkey ON public.dummy USING btree (id);

alter table "public"."dummy" add constraint "dummy_pkey" PRIMARY KEY using index "dummy_pkey";

grant delete on table "public"."dummy" to "anon";

grant insert on table "public"."dummy" to "anon";

grant references on table "public"."dummy" to "anon";

grant select on table "public"."dummy" to "anon";

grant trigger on table "public"."dummy" to "anon";

grant truncate on table "public"."dummy" to "anon";

grant update on table "public"."dummy" to "anon";

grant delete on table "public"."dummy" to "authenticated";

grant insert on table "public"."dummy" to "authenticated";

grant references on table "public"."dummy" to "authenticated";

grant select on table "public"."dummy" to "authenticated";

grant trigger on table "public"."dummy" to "authenticated";

grant truncate on table "public"."dummy" to "authenticated";

grant update on table "public"."dummy" to "authenticated";

grant delete on table "public"."dummy" to "postgres";

grant insert on table "public"."dummy" to "postgres";

grant references on table "public"."dummy" to "postgres";

grant select on table "public"."dummy" to "postgres";

grant trigger on table "public"."dummy" to "postgres";

grant truncate on table "public"."dummy" to "postgres";

grant update on table "public"."dummy" to "postgres";

grant delete on table "public"."dummy" to "service_role";

grant insert on table "public"."dummy" to "service_role";

grant references on table "public"."dummy" to "service_role";

grant select on table "public"."dummy" to "service_role";

grant trigger on table "public"."dummy" to "service_role";

grant truncate on table "public"."dummy" to "service_role";

grant update on table "public"."dummy" to "service_role";


